### ISSUE TITLE
How to programmatically change page?

### ISSUE THREAD

**Issue by Giulico** [TylerBarnes/gatsby-plugin-transition-link#114]
Hi,
I wanter if there is a way to programmatically change the page calling an API such as `navigate(...)` with all the `<TransitionLink ... >` properties.

I'm working on a project with some webgl in it, and sometimes I don't have a real DOM where to append a link.

Thank you.

**Comment by TylerBarnes** [comment]
Hey @Giulico , sounds really interesting! I'd love to see what you're working on.

If you check the function `triggerTransition()` I believe it will work for you. If I remember correctly this is undocumented but it you look at the `<TransitionLink />` component you should be able to see how it's working https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/32aafd2cc413f4f1e6307bbda41c29418ceb2c39/src/components/TransitionLink.js#L38

Theoretically all you will need to do is pass the same arguments to the function in the way they're being passed in that file.

**Comment by TylerBarnes** [comment]
Oh, it also requires access to the context state, so you'll need to pass that to the function as well (`...context`)

**Comment by Giulico** [comment]
Thank you @TylerBarnes I made it work with the `triggerTransition(...)` func! 👍

**Comment by TylerBarnes** [comment]
Good to hear!

**Comment by mjsarfatti** [comment]
In case anybody stumbles here and needs to change page programmatically, this is how I've done it using hooks:

In your **page.js**

```js
// import React etc.

...

import TransitionLink from 'gatsby-plugin-transition-link';
import { Consumer as TransitionLinkConsumer } from 'gatsby-plugin-transition-link/context/createTransitionContext';
import { triggerTransition } from 'gatsby-plugin-transition-link/utils/triggerTransition';

...

// Your functional component
const Page = () => {
  
  ...

  // We need our context values
  const transitionLinkContext = useContext(TransitionLinkConsumer);

  // TransitionLink expects an event to be passed, so we create a fake one:
  const FakeEvent = new Event('click');
  FakeEvent.persist = () => {};

  // We can finally call "triggerTransition"
  triggerTransition({
    event: FakeEvent,
    to: `/${activeSection.current}`,
    exit: {
      length: 0.3,
    },
    entry: {
      length: 0.3,
    },
    ...transitionLinkContext,
  });

  ...

  return (

    ...

  );
};
```

Ps: @TylerBarnes one thing: React doesn't like it that we pass the Consumer to `useContext`, it wants us to be provided with the context itself... it would be awesome if 'gatsby-plugin-transition-link/context/createTransitionContext' exported the context itself as well (if you could take a look at my solution above and see if you notice any drawbacks, I'd be happy to do a PR)

**Comment by TylerBarnes** [comment]
@mjsarfatti this looks awesome! I'd love a PR. The one thing I would change is to make it so triggerTransition doesn't have to have an event if event is undefined (or false?). Thanks for looking into that!!
What do you think about `useTriggerTransition` as the hook name?

**Comment by mjsarfatti** [comment]
@TylerBarnes sorry for the late reply, I was investigating a problem with my app using a stale TransitionLinkConsumer, but it ended up not being caused by gatsby-plugin-transition-link.

What if the call was:  
`const triggerTransition = useProgrammaticTransition()` ?

And yes I agree on the optional event.

**Comment by mjsarfatti** [comment]
#157 👌

(I went with your suggestion, `useTriggerTransition`)

**Comment by caelinsutch** [comment]
How do you change pages programatically with the new hook that was merged? Is there any documentation on it?

**Comment by mjsarfatti** [comment]
I don't think it's in the docs yet, but you can see a demo here:
https://gatsby-plugin-transition-link.netlify.app/programmatic/b
and a sample code here: https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/master/example/src/pages/programmatic/b.js

**Comment by caelinsutch** [comment]
Is there a way to do this with the AniLink default transitions? I'm trying to use the swipein transition.

**Comment by mjsarfatti** [comment]
I think if you use the programmatic approach you'll have to build the transition yourself...

**Comment by gimoteco** [comment]
Would be awesome having the AniLink transitions available through the programmatic api. Maybe something like:
```javascript
const navigate = useAniLink("paintDrip");
<button onClick={() => navigate("/some-router"); 
```

**Comment by MutableLoss** [comment]
I'm surprised this issue is what I ran across when trying to find a way to use the library programmatically. Only after implementing this directly, did I find out there was an addition of a hook over a year ago. 

Is there a reason that documentation for the hooks doesn't really exist on the site, and is limited to a few obscure examples? This is some game-changing functionality when you need to avoid wrapping additional components, especially when rendering thousands of buttons.
