### ISSUE TITLE
AniLink compiling with warning

### ISSUE THREAD

**Issue by angelod1as** [TylerBarnes/gatsby-plugin-transition-link#119]
When importing AniLink the compiler throws a warning. When I remove ```import AniLink from 'gatsby-plugin-transition-link/AniLink';``` the warning goes away. The message:

```zsh
Compiled with 1 warnings
warning in ./node_modules/gatsby-plugin-transition-link/components/Layout.js
Critical dependency: the request of a dependency is an expression
```

**Steps to reproduce:**

```yarn add gatsby-plugin-transition-link gsap``` then add ```import AniLink from 'gatsby-plugin-transition-link/AniLink';``` in your component.

**What should happen:**

The compiler should throw zero warnings.

**What happens:**

The compiler should throws a warning.

**Other infos**

```
"gatsby": "2.13.21",
"gatsby-plugin-transition-link": "^1.12.4",
"gsap": "^2.1.3",
```

**Comment by angelod1as** [comment]
my bad, I forgot to reference it in `gatsby-config`

**Comment by TylerBarnes** [comment]
No worries! Let me know if you run into any other issues. Happy to help if I can
