### ISSUE TITLE
useSpring

### ISSUE THREAD

**Issue by aprather51** [TylerBarnes/gatsby-plugin-transition-link#125]
Following example from #34, using `{ spring }` ...

```jsx
const MySpring = ({ text }) => (
  <TransitionState>
    {({ mount }) => (
        <Spring
          to={{
            transform: `translateY(${mount ? 0 : '100px'})`,
            opacity: mount ? 1 : 0,
          }}
        >
          {props => <div style={props}>{text}</div>}
        </Spring>
      )}
  </TransitionState>
)
```

It was success, Now I am achieving for `useSpring` https://www.react-spring.io/docs/hooks/basics, hook with `TransitionState` Any examples you could share of using hook?  My recent try...

```jsx
 function MySpring({ children }) {
	return (
 		<TransitionState>
 			{({ transitionStatus, exit, entry }) => {
 				const mount = [ 'entering', 'entered' ].includes(transitionStatus);
				const seconds = mount ? entry.length : exit.length;
				const Animated = animated.div;
 				const props = useSpring({
 					transform: `translateY(${mount ? 0 : '100px'})`,
 					opacity: mount ? 1 : 0,
 					config: { duration: seconds * 1000 }
 				});

 				return <Animated style={props}>{children}</Animated>;
			}}
 		</TransitionState>
 	);
 }
```
It didn't make sense to me on how I did it. I end up getting an error...
```
React Hook "useSpring" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function
```
It's clear that, I should have separate component rather than doing it inline. Unfortunteky, I cannot come up with idea of doing it? unless there's way to make hooks for TransitionState *eg* `useTransitionState`?

**Comment by TylerBarnes** [comment]
Hey @aprather51 , there is a `useTransitionState` hook actually! It hasn't made it's way to the docs yet but you should be able to import it like `import { useTransitionState } from 'gatsby-plugin-transition-link/hooks'`. It should return the same arguments as `TransitionState`.

Another thing that isn't in the docs yet is that you should be able to get `mount` directly from transition state. There's also a `current` variable to get the transition values of the current page instead of checking mount.

Try something like:
```jsx
 function MySpring({ children }) {
        const { transitionStatus, current, mount } = useTransitionState();
	const seconds = current.length;

	const Animated = animated.div;
 	const props = useSpring({
 	        transform: `translateY(${mount ? 0 : '100px'})`,
 		opacity: mount ? 1 : 0,
 		config: { duration: seconds * 1000 }
 	});

	return <Animated style={props}>{children}</Animated>
 }
```

**Comment by aprather51** [comment]
Awesome, it worked now! is there a hook for `TransitionLink` too?

**Comment by TylerBarnes** [comment]
@aprather51 there isn't yet as I'm not sure what one would look like. Do you have any ideas?

**Comment by aprather51** [comment]
The way I see as of now, I don't think it need hook. `TransitionLink`. its more of wrapping/nesting component than state. if I come up with Idea, I certainly will share it with you.

Great job with TL and Thank you for helping.
