### ISSUE TITLE
Pause transition timeline for two seconds?

### ISSUE THREAD

**Issue by aprather51** [TylerBarnes/gatsby-plugin-transition-link#126]
The the timeline goal: 
(clicking on page 2) &rarr; Animate Entry &rarr; Animate duration (1.5s) &rarr; Animate exit &rarr;  [ pause for 2s with `setTimeout()` ] &rarr; (entering page 2) &rarr; Animate Entry &rarr; Animate duration. 1.5s &rarr; Animate Exit. 

I making progress, But having issue:
(clicking on page 2) &rarr; Animate Entry &rarr; Animate duration (1.5s) &rarr; Animate exit &rarr;  [ pause for 2s with `setTimeout()` ] &rarr; (entering page 2 with No animation 😔) 

I believe already ran duration pause period. 
here's the code
**MySpring.js**
```jsx
...
import TransitionLink from 'gatsby-plugin-transition-link';
import { useTransitionState } from 'gatsby-plugin-transition-link/hooks';

function MySpring({ children }) {
	const { current, mount } = useTransitionState();

	const Animated = animated.div;
	const props = useSpring({
		transform: `scale(${mount ? 1 : 0.9})`,
		opacity: mount ? 1 : 0.5,
		config: { duration: current.length * 50 }
	});

	return <Animated style={props}>{children}</Animated>;
}

const SpringLink = ({ to, children }) => (
	<TransitionLink to={to} exit={{ length: 2 }} entry={{ delay: 0.7 }}>
		{children}
	</TransitionLink>
);

export { MySpring, SpringLink };
```
**PageLoad.js**
```jsx
...
import {  MySpring } from 'components';

function PageLoader({ children }) {
	const [ pageRender, setPageRender ] = useState(true);

	useEffect(() => {
		setTimeout(() => setPageRender(false), 2000); 
	}, []);

	return (
		<div>
			{pageRender ? <h1>loading...</h1> : <MySpring>{children}</MySpring>}
		</div>
	);
}

```
Any suggestion? Are there a way to pause Transition in between time?

**Comment by TylerBarnes** [comment]
Hey again,
Your exiting page has a duration of 2 seconds and your entering page is delayed by 700ms which means your entering page will be animating during the 2 second exit animation.

If you want your exiting page to have a 1.5sec animation and your entering page to delay for 2 seconds try this:
```jsx
const SpringLink = ({ to, children }) => (
	<TransitionLink to={to} exit={{ length: 1.5 }} entry={{ delay: 2 }}>
		{children}
	</TransitionLink>
);
```

If you mean that you want your exiting page to delay for 2s after your exiting page is finished it's 1.5s animation then you should set `entry={{ delay: 3.5 }}`

**Comment by aprather51** [comment]
Hello again, 
> _If you mean that you want your exiting page to delay for 2s after your exiting page is finished it's 1.5s animation then you should set `entry={{ delay: 3.5 }}`_

When I set entry delay of 3.5, Nav menu disappears! See here...

![page-transition-nav-disappear](https://user-images.githubusercontent.com/10257247/64494553-1309b580-d254-11e9-9057-c953c6925fa8.gif)

I couldn't figure out why but had to keep `delay` at same value number as `length`. so nav won't disappear... Why is that?

I realize I did a poor job in writing, my explanation wasn't clear which ends up with the answer I wasn't expecting for, I guess was in rush other day.  Allow me rephrase everything.  Starting with .gif example....

![page-transition](https://user-images.githubusercontent.com/10257247/64494564-359bce80-d254-11e9-85ad-932bb77f83fb.gif)

The motion graphic example above is what I ~~wanted to~~ almost achieved.  You can see after clicking on "About" nav link, this give "delay" of 2 to 3 seconds before entering *About* page. Scoping at duration range (2 to 3s), two components are switching between each others. The *page* component will spend 1.5s "exiting" time (*shrinking size then fade out*). Then switching to *progress* component which spend assumedly another 1.5s "pause" *progress bar appears and disappear* 

Here's code that I did...

**pageloader.js**

```jsx
...
import PageTransition from './components/PageTransition';
import ProgressBar from './components/ProgressBar';

function PageLoader({ children }) {
	const [ pageRender, setPageRender ] = useState(true);
	const [ currentProgress, setCurrentProgress ] = useState(0);

  //exiting time
	useEffect(() => {
		setTimeout(() => setPageRender(false), 2000); //2200 - old
	}, []);

  //pause time
	useEffect(() => {
		setTimeout(() => setCurrentProgress(100), 1000);
	}, []);
  
return(
 	<div>
	     {pageRender ? (
				<Page style={props}>
					<Text>Loading...</Text>
					<ProgressBar progress={currentProgress} />
				</Page>
			) : (
				<MySpring>{children}</MySpring>
			)}
		</div>
  );
}

```

**PageTransition.js**
```jsx
...
import { useTransitionState } from 'gatsby-plugin-transition-link/hooks';

function PageTransition({ children }) {
	const { current, mount } = useTransitionState();

	const Animated = animated.div;
	const props = useSpring({
		// transform: `translateY(${mount ? 0 : '100px'})`,
		transform: `scale(${mount ? 1 : 0.9})`,
		opacity: mount ? 1 : 0.5,
		// config: { duration: '250ms' }
		config: { duration: current.length * 50 }
	});

	return <Animated style={props}>{children}</Animated>;
}


export default PageTransition;
```
**Nav.js**
```js
...
import TransitionLink from 'gatsby-plugin-transition-link';

const TransitionLink = ({ to, children }) => (
	<TransitionLink to={to} exit={{ length: 1.5 }} entry={{ delay: 1.5 }}>
		{children}
	</TransitionLink>
);

export default TransitionLink;
```
And Result...

![close-glicth](https://user-images.githubusercontent.com/10257247/64494832-3b46e380-d257-11e9-928b-48a595c87cfd.gif)

Not perfect yet, there are some glitch. The page did not fade in as they enter (*after progress bar*). Probably, it have something to do with `setTimeout`. The progress bar are too fast. 

I had to adjust transition-link's `delay` , `length`, `entry`, `exiting` a lot to get a perfect sequence, unfortunately it have been struggle, this is when mix with `setTimeout` with Transition Link. Probably sound too over-complicated or over-engineered. I was hoping to find a way to avoid this. Any suggestions?

Hope this time my explanation is clear. and Thanks in Advance

**Comment by TylerBarnes** [comment]
Animations across multiple pages with multiple elements are complex by nature, so you'll usually have to do a lot of tweaking to get it to work exactly as you want. This is actually why I usually use GSAP with TransitionLink, it's a lot easier to control many different elements from one place that way, rather than lining everything up perfectly in different places. 

One big problem is that with spring based transitions, there isn't a straight forward way to tell when all animations on a page are done or how far along all spring based transitions on the current page have progressed (as far as I know), so you have to mix spring based animations with duration based transitions which can be tough. IMO, spring based animations work well for simple animations but become really difficult when multiple stages of animation are involved.

For your issue with your menu dissapearing, my guess is that your menu is part of your page. If you add it to a layout it should remain. Your exiting page fully unmounts once the length has elapsed, then the entering page doesn't mount until the delay elaspses. If the menu is part of each page, it will only show up while a page is mounted. A layout will solve that, check the docs for how to use a layout https://transitionlink.tylerbarnes.ca/docs/installation/

**Comment by aprather51** [comment]
>This is actually why I usually use GSAP with TransitionLink, it's a lot easier to control many different elements from one place that way
I agree! As matter of fact, GSAP was my first try but I end up using react-spring. I ll go back into GSAP. Any example using  GSAP with Transition-Link? 

>A layout will solve that, check the docs for how to use a layout https://transitionlink.tylerbarnes.ca/docs/installation/
I will look into it. 

Thank you.
