### ISSUE TITLE
Remove unused dependency cross-env

### ISSUE THREAD

**Issue by jaller94** [TylerBarnes/gatsby-plugin-transition-link#127]
https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/8ceabb9d02542543f1b0c4f27cddc23e8d609f0c/package.json#L41

The GitHub search says, that it's not used:  
https://github.com/TylerBarnes/gatsby-plugin-transition-link/search?q=cross-env&unscoped_q=cross-env

**Comment by TylerBarnes** [comment]
Thanks for flagging this. I believe this was in my old build/npm-release script. I'll remove it
