### ISSUE TITLE
How can I disable style.css from this plugin?

### ISSUE THREAD

**Issue by yuuta1999** [TylerBarnes/gatsby-plugin-transition-link#137]
First of all, this plugin is awesome. It saved me tons of time compare to [react-transition-group](https://github.com/reactjs/react-transition-group). But I have a problem about default style that this plugin added.  So before I used, my footer looked like this.
![Screenshot (24)](https://user-images.githubusercontent.com/30456893/66094171-ea6d9680-e547-11e9-98d2-4ba9cf17dedc.png)

And after I used.
![Screenshot (25)](https://user-images.githubusercontent.com/30456893/66094249-2acd1480-e548-11e9-8a5d-63b4c062d9eb.png)

When I first got this problem, I didn't know what I'd done wrong exactly. So I popped off the devtool and I noticed that it inserted to my layout 2 div tags with the class names `tl-edges` and `tl-wrapper`. After a few tries, this property is probably the problem.
![Screenshot (26)](https://user-images.githubusercontent.com/30456893/66094597-6caa8a80-e549-11e9-8122-a7d682b4bfb2.png)
After I changed this property value, it went back to the first image. Then I thought I could override that with my CSS file. But the main problem is that this plugin don't accept or recognize my override CSS file. So how can I fix that? Any comments are appreciated to me.

**Comment by TylerBarnes** [comment]
Apparently theme shadowing works for plugins too. So you could override that CSS file using shadowing. Otherwise you should be able to add `.tl-wrapper .tl-edges { overflow-x: unset; }` to your CSS

**Comment by TylerBarnes** [comment]
Also, thanks for the compliment. I'm glad you're finding this plugin useful!

**Comment by watarutmnh** [comment]
@TylerBarnes
I tried to overwrite style with mysite/src/gatsby-plugin-transition-link/style.css but seems not working.
Am I having wrong path for shadowing?
I love your plugin anyway!

**Comment by TylerBarnes** [comment]
Hmm, tbh I'm not 100% sure. Maybe make sure you're on the latest version of Gatsby and try again. Otherwise it might be worth just adding some additional CSS to override that file.

**Comment by yuuta1999** [comment]
Hey @TylerBarnes, I'm sorry for my late response. I think shadowing is worked perfectly but it seemed overwhelming for me to add shadowing to my codebase. And yeah, you can add additional CSS to override that file like below:
```
// Fix gatsby-transition-link-plugin default style.
main {  // Or any parent elements of these 2 two classes.
  .tl-edges {
    overflow-x: unset;
  }

  .tl-wrapper {
    float: unset;
  }
}
```
This is my solution to this issue. I will close this issue. Keep working on this great project.

**Comment by TylerBarnes** [comment]
Thanks @yuuta1999 ! Glad to hear it's working for you.

**Comment by watarutmnh** [comment]
@TylerBarnes tried with latest gatsby but it doesn't shadow original style.css. but it solved with additional css to override. cheers!
