### ISSUE TITLE
TransitionPortal not loading layout correctly on first visit 

### ISSUE THREAD

**Issue by frazerf** [TylerBarnes/gatsby-plugin-transition-link#141]
Hi there,

I've run in to a problem when I first visit my site - https://zen-bartik-a5d694.netlify.com/. There's a sidebar which should be present on the left hand side of the page but on initial load it's now being added to the bottom of the page.

I'm using TransitionPortal with AniLink which maybe the problem but I'm not 100% sure. 

My Layout.js file looks like this - 

```
import 'bootstrap/dist/css/bootstrap.min.css';
import './../styles/global.scss'
import React from 'react'
import PropTypes from 'prop-types'
import Helmet from 'react-helmet'
import { StaticQuery, graphql } from 'gatsby'
import { TransitionPortal } from "gatsby-plugin-transition-link";

import Sidebar from './sidebar'

const Layout = ({ children }) => (
  <StaticQuery
    query={graphql`
      query SiteTitleQuery {
        site {
          siteMetadata {
            title
          }
        }
        contentfulNavigation {
          navigationItems {
            id
            navigationTitle
            navigationLink
          }
        }
      }
    `}
    render={data => (
      <>
        <Helmet
          title={data.site.siteMetadata.title}
          meta={[
            { name: 'description', content: 'Sample' },
            { name: 'keywords', content: 'sample, something' },
          ]}
        >
          <html lang="en" />
        </Helmet>
        <div className="outer-container">
          <TransitionPortal level="top">
            <Sidebar nav={data} />
          </TransitionPortal>
          <div className="main-content">
            {children}
          </div>
        </div>
      </>
    )}
  />
)

Layout.propTypes = {
  children: PropTypes.node.isRequired,
}

export default Layout

```

When I visit a page another page on the site it then works fine which makes me think it's not mounting correctly the first time.

Could any shed some light on what I'm doing wrong?

**Comment by TylerBarnes** [comment]
Hey @frazerf , I have a simple fix for you!
The transition portal is meant to be used for animation elements rather than page content. You should use a persistent layout component to keep your sidebar. Have a look at this issue for more info https://github.com/TylerBarnes/gatsby-plugin-transition-link/issues/138#issuecomment-539102826

Let me know if that doesn't solve your issue and I can give you a hand

Thanks!

**Comment by frazerf** [comment]
Such a simple fix! Thanks for the @TylerBarnes. Love the plugin by the way!
