### ISSUE TITLE
Use TransitionLink, but on a button

### ISSUE THREAD

**Issue by webjay** [TylerBarnes/gatsby-plugin-transition-link#142]
#question
I assume that I would need to style the `TransitionLink` element to look like a button if I want it to look and act like a button?
There is currently no other way?

**Comment by TylerBarnes** [comment]
@webjay what your use-case?

**Comment by webjay** [comment]
@TylerBarnes The use-case is that when you click on a button [here](https://q.weareheadlight.com/im-usually-5-minutes-late.html), we would like [this](https://user-images.githubusercontent.com/99781/66379219-52433780-e9b5-11e9-91e2-4336e3e60c89.gif) animation.

**Comment by TylerBarnes** [comment]
@webjay I think for accessibility those should be links. The site you linked is using the button-looking elements to navigate to different pages which makes them hyperlinks (see http://www.webaxe.org/proper-use-buttons-links/). 

I think applying transition-link to buttons is outside the scope of this package as buttons are typically for actions that happen on the current page like opening a modal. 

IMO if you're navigating to a new page it should be via a link, not a button. I think in Gatsby you'd have to do something hacky like `<button onClick={navigate(`/other-page`)}>...</button>` to make it work anyway.
If you do want to use buttons, I would recommend skipping transition-link and don't go to a new route when you click those buttons, instead keep your survey data in state. For a survey this likely makes more sense anyway.

I'm happy to be wrong though! :)

**Comment by webjay** [comment]
@TylerBarnes I think you are correct! :)

**Comment by TylerBarnes** [comment]
@webjay sounds good. Cool site by the way!
Let me know if you run into any other issues!
