### ISSUE TITLE
Duplicate history states when using pathPrefix

### ISSUE THREAD

**Issue by andresmrm** [TylerBarnes/gatsby-plugin-transition-link#143]
When GatsbyJS `pathPrefix` config is set, navigation through `TransitionLink` inserts duplicated states in browser history. So we have to press browser "back" button twice to return to previous page.

It seems the problem is in this line:
https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/f98360bee46998d64597f9f21ec06704ae138eed/src/gatsby-browser.js#L11
`location.pathname` includes the `pathPrefix`, but `window.__tl_desiredPathname` don't. So they will always differ, doing the `navigate(window.__tl_desiredPathname);`, inserting a duplicate state in history.

**Comment by TylerBarnes** [comment]
Good find!! I think a fix for this should be pretty simple.

Here -> https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/bd76f4eccfb7f329f67e39dbc2594d129d04bbf1/src/utils/triggerTransition.js#L27 `to` needs to be wrapped with `withPrefix` -> https://www.gatsbyjs.org/docs/gatsby-link/#add-the-path-prefix-to-paths-using-withprefix

**Comment by andresmrm** [comment]
Hi, @TylerBarnes !

Any idea about when you'll have time to check my PR?

Thanks!

**Comment by TylerBarnes** [comment]
Sorry for the delay @andresmrm , I've been super busy working on a new source plugin for Gatsby!  I'm sorting through about 300 github emails right now :| haha. I'll check this out either this evening or tomorrow and merge/release or get back to you. Thank you for the reminder!

**Comment by TylerBarnes** [comment]
@andresmrm thanks for your PR (https://github.com/TylerBarnes/gatsby-plugin-transition-link/pull/144), and apologies again for the delay!
This is published in `gatsby-plugin-transition-link@1.13.1`

**Comment by andresmrm** [comment]
Thank you! =D
