### ISSUE TITLE
Remove transition state & status from page props

### ISSUE THREAD

**Issue by TylerBarnes** [TylerBarnes/gatsby-plugin-transition-link#145]
Currently each page is cloned in order to add additional props to it related to the transition. The reason for this was to try to make things as seamless and simple as possible, so that you could use the props without needing to hook anything up. This was a bad choice though as it causes unnecessary re-renders for people who aren't using these props at all. 
This is a potentially breaking change so should be released as part of V2

**Comment by TylerBarnes** [comment]
[These lines](https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/aeae1d3ecad18ed86b566e3b9e788cff534bef49/src/components/TransitionRenderer.js#L56-L58) should be changed to just `{children}`. The status passed in as a prop can also be removed as well as the `shouldComponentUpdate` lifecycle method. 
After making these changes, we should check if there are still unnecessary renders happening and adjust further if there are. The classname based on the status may need to be removed as well.

**Comment by NerdCowboy** [comment]
@TylerBarnes It appears you already addressed this in the branch V2-2 SHA: 350ea0c2018e8be74ed45505eee0de64b028149a

**Comment by TylerBarnes** [comment]
Good catch! To be honest I can't remember if that branch got very far. Thanks for the reminder. Let's keep this open so that ot doesn't get missed in v2. I will probably start a new branch for v2 still. I have more time to work on this project now, so things should start moving again.

**Comment by TylerBarnes** [comment]
This is now possible via a plugin option.

```javascript
    {
      resolve: 'gatsby-plugin-transition-link',
      options: {
        injectPageProps: false,
      },
    },
```

injectPageProps is true by default, in v2 it will be false by default
