### ISSUE TITLE
Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by webjay** [TylerBarnes/gatsby-plugin-transition-link#150]
I am seeing this error when I `yarn build` with version 1.16:

> Cannot read property 'state' of undefined

The property `entry` is `undefined`.

**Comment by webjay** [comment]
An example:

`./pages/about.jsx`:
```
export default function AboutPage({ entry }) {
  const { prevPath } = entry.state;

```

**Comment by TylerBarnes** [comment]
🤦‍♂️I'll check it out

**Comment by TylerBarnes** [comment]
This is fixed! Upgrade to `gatsby-plugin-transition-link@1.16.1`, last release could've used a bit more testing ;)
