### ISSUE TITLE
GSAP animation not working with GSAP 3.0.1

### ISSUE THREAD

**Issue by amcc** [TylerBarnes/gatsby-plugin-transition-link#156]
I just did a "yarn upgrade --latest" and got GSAP 3.0.1 - this broke Anilink without getting any erros, but it caused the links to happen instantly and not animate.

Rolling back to "gsap": "^2.1.3" has fixed everything.

There might be documentation on this, sorry if I missed something, but in case this is useful it might help someone else.

**Comment by milespratt** [comment]
Seeing similar broken transitions with gsap 3.0.2 and gatsby-background-image. The background images are loading instantly while the rest of the page animates.

Also solved by rolling back to gsap ^2.1.3

**Comment by TylerBarnes** [comment]
The upgrade to GSAP v3 is a major version because they've redesigned their internal API https://greensock.com/3/

The animations in AniLink will have to be updated to work with their new api changes.

**Comment by ajayns** [comment]
@TylerBarnes Is this issue resolved? I didn't know about this and went ahead using GSAP with AniLink with no major issues in transition so far. If that's not the case, maybe in the Readme, for now, we'll have to mention something like `yarn add gsap@^2.1.3` or so instead. Else it'd go on installing GSAP 3 and users will have no idea.

**Comment by TylerBarnes** [comment]
A fix for this is published in `gatsby-plugin-transition-link@1.18.0`. I decided this isn't a breaking change for this package, as the functionality of AniLink remains the same even though you need to upgrade to GSAP 3
