### ISSUE TITLE
Can't make use of classes

### ISSUE THREAD

**Issue by MrRobotjs** [TylerBarnes/gatsby-plugin-transition-link#16]
Before I would be able to use these for Links
```
className={mystyles.linkWrapper}
activeClassName={mystyles.active}
```
and now that I have replaced my `<Links>` with `<AniLink>` the classes doesn't even show up anymore and the active page class isn't appearing either which is a big problem since I rely on css quite a bit.

**Comment by TylerBarnes** [comment]
Great point. I have the code open already so I'll fix this right now!

**Comment by TylerBarnes** [comment]
Update to v1.3.3 and this is fixed :)

**Comment by TylerBarnes** [comment]
Sorry, update to 1.3.4 instead. 1.3.3 broke the fade transition.

**Comment by MrRobotjs** [comment]
Works perfectly fine now thanks!

**Comment by rikvanderkemp** [comment]
@TylerBarnes This seems to be broken in later versions. I have downgraded to 1.3.4 and it works again. 

Using GatsbyJs 2.0.76

**Comment by TylerBarnes** [comment]
Hey @rikvanderkemp , thanks for letting me know. Are you using transition link or ani link when you're having the issue? It's odd that it wouldn't work since that part of the code is the same. I guess something else must be interfering with it.

**Comment by TylerBarnes** [comment]
@rikvanderkemp I tested it out just now but I can't reproduce the issue. If you check at https://5c3a38f7cd86f000094ed960--transitionlink.netlify.com/ the three bottom links have all had their `to` prop changed to the page they're on to test the active class, then I've added `activeClassName="active"` and `className="test"` and both of those are showing up in the dom. I tested it out with anilink and transitionlink as well.

Are you able to put up a demo repo with the issue? It would be great to see in case there is a bug just when using a certain combination of props or something odd like that.

Thanks again for posting about it!

**Comment by rikvanderkemp** [comment]
@TylerBarnes I made a similar test based on the codebase I was working on. Got the same result, however, I have cleared my node_modules folder, reinstalled the plugin. Locally that seemed to do the trick. I redeployed to Netlify but it didn't change, I suspect a caching issue at Netlify to be honest. Created a new site there and it works. So I suppose this was a false alarm. I do suspect an issue with Gatsby and active links, when you refresh the page it fails to mark the link as active (due to a trailing slash in the URL). I doubt that has anything to do with this plugin. Sorry for the troubles.

**Comment by TylerBarnes** [comment]
Ah, that makes sense. You can clear the cache at netlify if you go to deploys and click the dropdown that says "Trigger deploy" in the top right of the deploy history. In the dropdown there should be a button that says "Clear cache and deploy site".

You also might find this plugin useful in dealing with trailing slashes.
https://www.gatsbyjs.org/packages/gatsby-plugin-force-trailing-slashes/

<img width="1219" alt="screen shot 2019-01-13 at 1 02 15 pm" src="https://user-images.githubusercontent.com/14190743/51090640-cc4ed480-1733-11e9-9b8b-7cefdfeeb73c.png">

**Comment by TylerBarnes** [comment]
Also, thanks for debugging, I appreciate it!

**Comment by rikvanderkemp** [comment]
> Ah, that makes sense. You can clear the cache at netlify if you go to deploys and click the dropdown that says "Trigger deploy" in the top right of the deploy history. In the dropdown there should be a button that says "Clear cache and deploy site".
> 
> You also might find this plugin useful in dealing with trailing slashes.
> https://www.gatsbyjs.org/packages/gatsby-plugin-force-trailing-slashes/
> 
> <img alt="screen shot 2019-01-13 at 1 02 15 pm" width="1219" src="https://user-images.githubusercontent.com/14190743/51090640-cc4ed480-1733-11e9-9b8b-7cefdfeeb73c.png">

Excellent tip! Thanks!
