### ISSUE TITLE
Conflict with GSAP

### ISSUE THREAD

**Issue by ashussen** [TylerBarnes/gatsby-plugin-transition-link#195]
Hey there,

Really weird bug as this should work flawlessly with GSAP.
On my site the GSAP x & y calculation is completely off after I use the TransitionLink.

Here is the code for the onLoad GSAP animation: 
```
  let animEl = {}
  React.useEffect(() => {
    var tl = gsap.timeline();
    tl.from(animEl.image, { x: -800, duration: 0.5})
  }, [animEl])
```

The final CSS for the `animEl.image` is `transform: translate(0px);` if the TransitionLink is not being used.
But with TransitionLink, the final CSS is `transform: translate(-501.811px)`. 

Not sure what caused the miscalculation. All other animation type, such as autoAlpha works normally.

Here is the only I use for TransitionLink, that even applied on a different element. One is image, and the other is a link.
```
<TransitionLink to={`/${territory.slug}`} exit={{length: 1}}>{territory.name}</TransitionLink>
```

**Comment by TylerBarnes** [comment]
Hey @ashussen , that's really odd. TransitionLink itself isn't using GSAP at all so I'm not sure what could cause that. If you can share a simple reproduction repo I'm happy to take a look and see if I can figure it out.

**Comment by ashussen** [comment]
@TylerBarnes, thanks for your response.

I am still not sure what the problem is, the pixel calculation is weird when combining GSAP with TransitionLink.

I ended up using the `fromTo` on gsap, forcing the element to ends in a specific pixels.
```
      tl.fromTo(animEl.image, { x: -800 }, { x: 0, duration: 0.5 })
```

**Comment by TylerBarnes** [comment]
Huh, super weird. glad you found a workaround. Happy to take a look at it if it comes up again
