### ISSUE TITLE
How to pass props to Layout when its removed

### ISSUE THREAD

**Issue by hellofantastic** [TylerBarnes/gatsby-plugin-transition-link#196]
Awesome work BTW. After I figured out the remove layout ( config resolve etc) for a fixed header nav and studied gsap greensock, pages transitions are slick.

BUT I'd like to pass props to the layout depending  on different pages and sometimes on a page that has a slider per slide . some pages or some slides may have dark or light header image so layout nav needs to adjust color of text and logo.

**Comment by orinokai** [comment]
The layout component gets passed the same props as the page it wraps (see the example [here](https://www.gatsbyjs.org/docs/ssr-apis/#wrapPageElement)), including location, data, etc. As a workaround it might be useful to conditionally render different items depending on the page.

**Comment by hellofantastic** [comment]
Okay so perhaps I could try on a slide transition callback send a prop up to the page and check for it I'm the  layout pass a prop into nav to adjust its colors. Or introduce a global state context/redux and set it and connect nav to that

**Comment by TylerBarnes** [comment]
@hellofantastic I think you might be looking for the `state` prop!

See here https://transitionlink.tylerbarnes.ca/docs/transitionlink/#props-and-options (scroll down to "State option"

```
exit={{
  state: {
    thisIs: 'passed to the exiting page'
  }
}}
entry={{
  state: {
    thisIs: 'passed to the entering page'
  }
}}
```

In the example site https://gatsby-plugin-transition-link.netlify.app/ if you click the link in the middle that says "Go to page 2 that way ☝️and give us a dark theme when we get there." you can see this in action.

Let me know wether that's what you're looking for or not!

**Comment by hellofantastic** [comment]
Okay will be in this, this coming week.

**Comment by hellofantastic** [comment]
Should have commented on this earlier, got it working via state prop, thanks!
