### ISSUE TITLE
Implicit use of prefers-reduced-motion

### ISSUE THREAD

**Issue by BarrBozzO** [TylerBarnes/gatsby-plugin-transition-link#205]
Some days ago spent hours trying to figure out what's wrong with transition animation.
I think we should mention `prefers-reduced-motion` use in docs. Or at least `console.warn` about it in develop mode.
I would also recommend to add config option to remove such check.

What do you think?

**Comment by TylerBarnes** [comment]
I like the idea of warning in the console in development mode 👍 

Thanks for this idea

**Comment by TylerBarnes** [comment]
Published in `gatsby-plugin-transition-link@1.19.0`

**Comment by BarrBozzO** [comment]
@TylerBarnes  Great!
