### ISSUE TITLE
Can't resolve 'gatsby-plugin-transition-link/AniLink'

### ISSUE THREAD

**Issue by BrieucKyo** [TylerBarnes/gatsby-plugin-transition-link#217]
Hi! I'm getting this error :

```
ERROR #98124  WEBPACK
Generating SSR bundle failed
Can't resolve 'gatsby-plugin-transition-link/AniLink' in '/Users/Brieuc/Sites/GITHUB/portfolio/src/components'
If you're trying to use a package make sure that 'gatsby-plugin-transition-link/AniLink' is installed. If you're trying to use a local file make sure that the path is correct.
File: src/components/Header.js
```

when i'm importing AniLink like this in src/components/Header.js :
```
import AniLink from "gatsby-plugin-transition-link/AniLink"

<AniLink paintDrip to="/works">
   Works
</AniLink>
```

I did ```yarn add gatsby-plugin-transition-link``` & then added ```gatsby-plugin-transition-link``` to the plugin array of gatsby-config.js

Any idea ?

**Comment by luchoster** [comment]
Running into the same issue, no matter what I do, it won't work.

**Comment by TylerBarnes** [comment]
Hey @BrieucKyo thanks for opening an issue. Can you share a reproduction repo of this issue? Did a recent upgrade cause the problem?

**Comment by gabrielste1n** [comment]
> Running into the same issue, no matter what I do, it won't work.

Same, It's been running fine for months now, did a fresh build (deleted yarn.lock and node modules and then Yarn install) now won't work at all no matter what.

**Comment by xaviemirmon** [comment]
Same here

**Comment by Hrishikesh-K** [comment]
@TylerBarnes yeah, a recent update caused this issue for me. I returned to edit my website after quite a few days now, and so, decided to update all dependencies. After editing tha package.json manually, I deleted my `package-lock.json` and `node_modules` folder to do a fresh install. The problem started after that.

The previous version I was using:

`"gatsby-plugin-transition-link": "^1.18.0",`
`"gsap": "^3.3.3",`

This works fine.

I updated it today to:

`"gatsby-plugin-transition-link": "^1.19.2",`
`"gsap": "^3.3.4",`

This causes the mentioned problem.

**Comment by Hrishikesh-K** [comment]
Another update: I checked the contents of the folder `gatsby-plugin-transition-link` inside my `node_modules` folder and it doesn't have any `src` folder in it. The downloads from Github releases page of this repo has `src\AniLink` folders in them. This is the possible cause of the issue.

**Comment by felixkwan** [comment]
Same here. just update to the latest version 
`"gatsby-plugin-transition-link": "^1.19.2",`

**Comment by jlison** [comment]
I am experiencing the same issue as well. I tried updating without success. As soon as I delete my `package-lock` Webpack won't be able to resolve `gatsby-plugin-transition-link/AniLink`.

**Comment by TylerBarnes** [comment]
Can anyone share a repo that has this issue?

**Comment by Hrishikesh-K** [comment]
I don't have a repo, but, here's the source of my website if it works: https://www.dropbox.com/s/8k4uuifdnsjwiul/HriTech.zip?dl=0

**Comment by BrieucKyo** [comment]
@TylerBarnes 
Here is a gatsby default starter with ```gsap``` & ```gatsby-plugin-transition-link``` installed.
https://github.com/BrieucKyo/gatsby-plugin-transition-link

**Comment by TylerBarnes** [comment]
Hey everyone, apologies for this! This was a publishing mistake 🤦 since it's been a while since I published this package I did it wrong. Upgrade to `gatsby-plugin-transition-link@1.20.0` for a fix!

I will be automating the publishing step and adding some tests to prevent this from happening again https://github.com/TylerBarnes/gatsby-plugin-transition-link/issues/218

**Comment by gabrielste1n** [comment]
Hey @TylerBarnes, thanks for jumping on this issue so quickly! I implemented the proposed fix but am now getting `WebpackError: ReferenceError: window is not defined` when trying to build. I wasn't getting this before, any ideas as to what the issue could be?

**Comment by Hrishikesh-K** [comment]
Oh my God, I am not the only one! I just opened a issue on Gatsby thinking I made some problem with my build. I was so lost, but, there's some hope maybe, afterall?

**Comment by gabrielste1n** [comment]
> Oh my God, I am not the only one! I just opened a issue on Gatsby thinking I made some problem with my build. I was so lost, but, there's some hope maybe, afterall?

Glad to hear I'm not the only one too

**Comment by TylerBarnes** [comment]
Checking it out now, should have a fix up shortly! It looks like that's due to a bug in the version that was incorrectly published. Def need to get some automated tests set up sooner than later

**Comment by TylerBarnes** [comment]
@gabrielste1n @Hrishikesh-K a fix is published in `gatsby-plugin-transition-link@1.20.2`!

**Comment by gabrielste1n** [comment]
> @gabrielste1n @Hrishikesh-K a fix is published in `gatsby-plugin-transition-link@1.20.2`!

amazing thank you, taking a look now!

**Comment by Hrishikesh-K** [comment]
Thanks for the quick fixed @TylerBarnes. All good now.

**Comment by TylerBarnes** [comment]
Great to hear! Let me know if anything else comes up

**Comment by ivanovicsolaro** [comment]
In my case, follow these steps:
- Remove node_modules, package-lock.json and gatsby-plugin-transition-link from package.json.
- yarn install
- yarn add gatsby-plugin-transition-link
- yarn add gsap
