### ISSUE TITLE
Anilink fade effect not working

### ISSUE THREAD

**Issue by danialdezfouli** [TylerBarnes/gatsby-plugin-transition-link#225]
fade effect is not working ...

"Fade to page 2" 
https://gatsby-plugin-transition-link.netlify.app/

**Comment by oliver-gomes** [comment]
@danialdezfouli Yep same with here just troubleshooted my gatsby app (reinstalled npm package) and the effect is gone. Is it because of the new gatsby update?

**Comment by claygiffin** [comment]
@TylerBarnes I am working on a project where we would really like to use the fade effect. Is there a workaround for the broken Anilink fade transition?

**Comment by ezralazuardy** [comment]
Any update to this?, i've try the official demo here: https://gatsby-plugin-transition-link.netlify.app/, and the fade seems doesn't work anymore. Maybe it's because the new gatsby update?, other animation like paintDrip still work fine tho..

**Comment by koniecznytomek** [comment]
Hello, I wrote some simple components with transition effects using gatsby-plugin-transition-link. You don't need additional libraries. In my free time I will try to write a more custom component for it. You can check it live on [https://gatsby-custom-transition-link.netlify.app/](url) My repo koniecznytomek/gatsby-transition-links. it's not a big deal, but it works :)

**Comment by ezralazuardy** [comment]
cool, will definitely will try it. thanks.

**Comment by wphowto** [comment]
Is this project no longer maintain? The example in this repo is not working either.

**Comment by TylerBarnes** [comment]
@wphowto this project is very seldomly maintained as I'm usually very busy. If anyone is interested in helping me maintain this project please reach out to me
