### ISSUE TITLE
broken with Gatsby@2.24.70

### ISSUE THREAD

**Issue by y0hnn** [TylerBarnes/gatsby-plugin-transition-link#236]
Hey,

It seems something in Gatsby@2.24.70 broke the animations. Maybe related to https://github.com/gatsbyjs/gatsby/pull/27261 ?

**Comment by joebentaylor1995** [comment]
Same here

**Comment by riginosk** [comment]
Same here, seems like trigger does not run at all. There is nothing is logged in the console.
exit={{
  trigger: ({ node, e, exit, entry }) => console.log(node, e, exit, entry)
  // here node refers to the DOM node of the exiting page
}}

**Comment by aaadamgo** [comment]
Yeah 100% broke for me yesterday when updating all my packages. Narrowed it down to the gatsby version. Running on 2.24.67 makes things work again. I was using a simple "cover" background color transition. Now, the colour being passed in was correct, but the swipe itself never used that colour. So although it didn't break animations, it definitely stopped doing what it was supposed to do.

**Comment by joebentaylor1995** [comment]
For me all of my custom transitions totally broke and nothing fired same as @riginosk

**Comment by TylerBarnes** [comment]
Hey everyone, I think I have a fix for this. 🤞 might take me a little bit to release it but I'm working on it

**Comment by TylerBarnes** [comment]
Hey yall! I just published a fix in `gatsby-plugin-transition-link@1.20.4`! Let me know if you run into any problems with it :)

**Comment by TylerBarnes** [comment]
Update to `gatsby-plugin-transition-link@1.20.5` because I broke builds in the last version 😆

**Comment by joebentaylor1995** [comment]
FFS Tyler 🤦🏼‍♂️ 

Kind regards,

Joe
