### ISSUE TITLE
TransitionLink/AniLink appears to make timers for setInterval and setTimeout faster

### ISSUE THREAD

**Issue by karomancer** [TylerBarnes/gatsby-plugin-transition-link#246]
Hey y'all! 

I'm noticing some weird behavior. After I converted some of my `Link`s to `AniLink`s, it seems as though the timers for `setInterval` and `setTimeout` go faster than before. I found that what was once 80ms before is now 30-35ms. 

If you watch the splash screen on my site, you can see there's a byline that updates occupation/hobbies with multiple `setTimeout`s.

| Before `AniLink` | After `AniLink` | 
| ----- | ----- | 
| ![ezgif com-gif-maker (11)](https://user-images.githubusercontent.com/482817/99056303-fac7b180-254e-11eb-9303-cac13209d70e.gif) | ![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/482817/99055082-5180bb80-254e-11eb-859b-10e020802362.gif) | 
| [See Before Live](https://5fae431d32443a00079403ab--karinachowtime.netlify.app/)  | [See After live](https://5fae4b7e6e985f000856b11c--karinachowtime.netlify.app/) |

Honestly it's hard to tell with the framerate of a gif, but it's actually very jarring.

[This is what the commit with the change](https://github.com/karomancer/portfolio/commit/a233070d95db3d4be7d9b7e740a97f9dd804cd9a) looked like.

Is there a known issue with sped up timers?

**Comment by TylerBarnes** [comment]
Interesting! 🤔 you're the first to report this actually 😅 
This plugin uses wrappers around `setTimeout` and `setInterval` to make them use `requestAnimationFrame` so that transitions are more consistent. I think we'll need to import these wrappers with a different name in that case 🤔 

See https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/d09fc98647a8721e3d64321cf41d96191b07261b/src/utils/triggerTransition.js#L2

**Comment by karomancer** [comment]
Ah! I was futzing around in the source to try to find the issue, but glossed right over that import.

> we'll need to import these wrappers with a different name in that case

Are you suggesting there's a name collision, or what do you mean? I would imagine since it's local to that that file, there wouldn't be, but maybe when it's bundled it does some funky stuff. I'll play around in that file too and see what I can figure out. 

Thanks for your very speedy reply!

**Comment by TylerBarnes** [comment]
Yeah I also would've thought there wouldn't be a problem there since it's being imported in those files and shouldn't be doing anything global, but there might be something funky going on. And perhaps the imported package is globally patching `setInterval` and `setTimeout` 😱 I hope not though haha.

**Comment by karomancer** [comment]
Well, if I look into `triggerTransition.js` code in `node_modules`, it looks like it's calling `setTimeout` on the `requestanimationframe-timer` library:

![Screen Shot 2020-11-13 at 10 27 29 AM](https://user-images.githubusercontent.com/482817/99107652-05a83380-259b-11eb-85cf-4cc750e2ff0d.png)

Do you have any thoughts on how to test? Or should I just update my timers to be 2x as long? 😂 

The other weird thing to me is that the timers aren't consistently faster by the same margin; it seems to be variable. Normally I would say that might be influence by the p5 sketch file I have running on the page, but without `AniLink` I didn't have an issue before with inconsistent timing.

**Comment by karomancer** [comment]
I noticed that the timers only appear quick for a short period of time before reverting back to the correct time. I have two ideas:

- Could be related to the `setTimeout`s shown above in that after they are done, it resets 
- Could be related to the preprocessing that Gatsby links do so that the transition is easy; does transition link or `AniLink` add to that as well? or does that just circle back to the above point?

**Comment by TylerBarnes** [comment]
It's hard to say but I don't think it'd be due to Gatsby Link. The most likely culprit is the request animation frame timer library. It might be that they temporarily patch setTimeout temporarily and then put it back after 🤔

**Comment by TylerBarnes** [comment]
I can't think of any other potential reasons unfortunately 😅

**Comment by karomancer** [comment]
No prob. Thanks for looking into it!

**Comment by karomancer** [comment]
I investigated more and still could not resolve the issue. I removed `AniLink` from my project and the issue resolved itself. Going to write my own transitions :)
