### ISSUE TITLE
Adding a extra white space abve my Navbar

### ISSUE THREAD

**Issue by WOLFIEEEE** [TylerBarnes/gatsby-plugin-transition-link#253]
I am deploying a site using strapi and gatsby . The site was running perfectlly fine untill I added the plugin as soon as I added the plugin it given a extra space above my navbar.

As I am building it using strapi so instead you try to run it . I am providing a netlify link of it and sharing the repo .
Have a look at it 
(repo is quiite messed up please ignore)

**Without gatsby-plugin-transition-link**
Netfliy link of buld before using the tranisiton :- https://beforeusingplugin.netlify.app/
Link of the Repo I Used:-https://github.com/WOLFIEEEE/Gatsby-portfolio/tree/Dark-mode-WithoutPlugin

**With gatsby-plugin-transition-link**
Netfliy link of buld after using the tranisiton plugin:-https://afterusingplugin.netlify.app/
Link of the Repo I Used:- https://github.com/WOLFIEEEE/Gatsby-portfolio/tree/Dark-mode 

I updated the repo as I have to use it but you can still see the error in those netlify links

**Comment by Hahlh** [comment]
![image](https://user-images.githubusercontent.com/45669613/104121626-044b7b00-5340-11eb-91da-f95b89cd7dce.png)

Removing the margin-top of 5rem from your body should fix the issue :+1:

**Comment by Hahlh** [comment]
The content below your header should shift up as well, if you do this, but it also seems that you tried to reposition it before. 
Removing the negative margin of 5rem on the hero class should bring things back to normal:

![image](https://user-images.githubusercontent.com/45669613/104121869-e2eb8e80-5341-11eb-85cc-502d7c2fbd9c.png)

**Comment by WOLFIEEEE** [comment]
Thanks for the Help It solved My Issue @Hahlh , Closing Isuue
