### ISSUE TITLE
Cannot style AniLink component 

### ISSUE THREAD

**Issue by aamorozov** [TylerBarnes/gatsby-plugin-transition-link#28]
I'm passing the style to AniLink as `style={{...style}}` but it doesn't seem to be applied. I've tried adding it directly but it seems like it is still using the default styles. Is it not supported by design?

**Comment by aamorozov** [comment]
Since the active styles are passed correctly, I think the issue is here https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/master/src/components/TransitionLink.js#L20, the activeStyle prop has been passed down to gatsby's Link component, while style prop is not.

**Comment by TylerBarnes** [comment]
You're right! I've just published v1.4.5 which passes the style prop through properly.
Thanks for noticing!

**Comment by aamorozov** [comment]
@TylerBarnes Excellent, thank you! I just forked to add a pr a second ago 😁
