### ISSUE TITLE
Mantained projects

### ISSUE THREAD

**Issue by michelebruno** [TylerBarnes/gatsby-plugin-transition-link#315]
Hey everyone,

looks like this project in not maintained any longer! Do you have any suggestion to replace this awesome plugin?

**Comment by TylerBarnes** [comment]
I was far more naive when I created this than I am now 😆Maintaining projects takes a lot of time! I'd also love to hear about alternatives if anyone knows of good ones. I'm happy to add them to the top of the readme.
I also think it could be cool to fork this project, improve some of the perf issues, and make it meta-framework agnostic, but I'm slightly wiser now and know I don't have time for that

**Comment by michelebruno** [comment]
You did such a great job that this plugin still works on my website! Sorry to hear that's been dismissed, I hope that the community will help you in case of bugs!
Thank you @TylerBarnes , I'll let you know if I find out any alternatives
