### ISSUE TITLE
Anilink blink/flash before transition

### ISSUE THREAD

**Issue by FreeKev** [TylerBarnes/gatsby-plugin-transition-link#39]
I'm getting [this strange blinking/flashing effect](https://youtu.be/5IGVnaUfq3I) on the whole page when I click an Anilink. Could it be an incompatible module? 

```
module.exports = {
  siteMetadata: {
    title: 'Example',
  },
  plugins: [
    `gatsby-plugin-transition-link`,
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography.js`,
      },
    },
    `gatsby-plugin-sass`,
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'example',
        short_name: 'example',
        start_url: '/',
        display: 'minimal-ui',
        icon: 'src/images/example.png', // This path is relative to the root of the site.
      },
    },
    'gatsby-plugin-catch-links',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages'
      }
    },
    'gatsby-transformer-remark',
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.app/offline
    // 'gatsby-plugin-offline',
  ],
}
```

**Comment by FreeKev** [comment]
Thank you for the offer, but you nailed it! It was a CSS issue.

One glance at the CSS and I saw it on the body element: 

`height: calc(100% + 150px); // Force page v-scroll`

Appreciate your work, and your advice in an article to customize more with TransitionLink and react-pose. I'll get there, and look forward to any tutorials. Thanks!

**Comment by GreatState** [comment]
We are expericing this issue on our site

https://www.greatstate.co/careers/jobs/senior-frontend-engineer

When you load the page you get a slight flicker. This is causing problems with google lighthouse scores. I did a test and removed the package and the Largest ContentFul Paint went from 9.3s to 1.1 and the Cumulative Layout Shift
0 went from 1.4s to 0!

We are using version 1.9.1 with gatsby 2.7.5

Current basic pages are scoring well below 30
https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.greatstate.co%2Fcareers%2Fjobs%2Fsenior-frontend-engineer%2F

I've done some tweaks and managed to get this to 72

https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2F6024f6502a23290008d3d50c--greatstate-dev.netlify.app%2Fcareers%2Fjobs%2Fsenior-frontend-engineer%2F

by far the biggest change was replacing transiiton link with gatsby layout

i'm wondering what i can do to fix the scores whilst using transition link?
