### ISSUE TITLE
Still get some Link functionality?

### ISSUE THREAD

**Issue by danboyle8637** [TylerBarnes/gatsby-plugin-transition-link#47]
I have just started to use TL and it's awesome. I actually am going to use AniLink on my latest website. But I have one question.... I will test this but I wanted to ask anyway...

Can you still use some of the Link functionality like the navigate function from gatsby? or hijacking the back button?

I want to run a few animations like menu's closing and other random things before the page navigates away.

**Comment by TylerBarnes** [comment]
You should be able to still use the navigate function but you'll have to control the page scroll position yourself. 
Currently the back button doesn't work in transition link although I was working on a fix for this recently.

If you want to close a menu before navigating I would first put it in a persistent layout component. Then add a click handler either on your AniLink or on a parent component to close the menu while the transition is happening.

If you want to get more custom and delay the transition and fire off a bunch of functions I would recommend writing a custom transition link. That way you can run any arbitrary function you want and you'll control the full timing of how everything is happening. If you check the source code for anilink you could copy the code for one of the AniLink components as a starting point. 
https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/master/src/AniLink/Fade.js

Let me know if that doesn't answer your question. :)

**Comment by danboyle8637** [comment]
@TylerBarnes Thanks so much. This does make sense. I just need to start playing around with my code. I like the idea of building a custom transition. Off to study I go. Thanks again for making this!

**Comment by TylerBarnes** [comment]
Awesome, glad you're enjoying it. Let me know if you need any more help.
