### ISSUE TITLE
`yarn link` development environment fails to start

### ISSUE THREAD

**Issue by lsirivong** [TylerBarnes/gatsby-plugin-transition-link#50]
Hi I'm trying to get the development environment set up so that I can try working on #49, but I'm having trouble with some missing dependencies.

I followed the steps in the readme, and I get this error when trying to start `gatsby develop` after running `yarn link gatsby-plugin-transition-link`

### `yarn develop` output from the `example` folder:

https://gist.github.com/lsirivong/0215c110951720f55ff6b3e5271e85ad

### `yarn watch` output from the root folder:

```
yarn watch
yarn run v1.13.0
$ yarn copy-files && babel -w src --out-dir lib --copy-files --ignore **/__tests__
$ mkdir lib || true && cp .eslintrc.json readme.md package.json lib
mkdir: lib: File exists
Successfully compiled 22 files with Babel.
```

### Node version:
v10.14.1

### Yarn version:
1.13.0

When I try adding the dependencies that the gatsby build complains about at the plugin root level (`react-dom`, `gsap`, `@reach/router`), the build succeeds, but the transitions don't work.

**Comment by TylerBarnes** [comment]
Hey @lsirivong , thanks for contributing!

Recently I've had the same errors and I haven't had time to look into it much further or update the docs.
What I've been doing in the meantime is npm linking those dependencies back the other way from my gatsby project to the lib folder.

so in the lib folder I would run `npm link /Users/username/github/project-name/node_modules/react-dom` for example, and then I repeat that for `gsap` and `@reach/router`.

It's not an ideal solution but it works!

**Comment by TylerBarnes** [comment]
@jlengstorf mentioned to me that the solution is to use workspaces but I haven't had the opportunity to investigate yet.

**Comment by jlengstorf** [comment]
`yarn link` has issues.

[Workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) accomplish the same thing, but without requiring a bunch of goofy linking.

I create a `package.json` a level up from my two packages and use that locally:

```json
{
  "private": true,
  "workspaces": [
    "package-one",
    "package-two"
  ]
}
```

Assuming the `name` from the `package.json` in `package-one` is also `package-one`, you do the following from the folder where that workspace `package.json` is:
```
yarn
yarn workspace package-one develop
```

(This assumes that you have a `develop` command set up in `package-one`.)

**Comment by TylerBarnes** [comment]
Awesome, thanks for the explanation @jlengstorf !
