### ISSUE TITLE
Pressing back during a transition causes bugs

### ISSUE THREAD

**Issue by flowen** [TylerBarnes/gatsby-plugin-transition-link#52]
Hi tyler, we spoke by email before.

[Here's an example](https://5c89301d48afbf00099f5196--techno-a3c803.netlify.com) of the bug. Click a link and press back while transitioning.

When you press back during a transition, the node contexts of the other page is still there is y first guess.

Suggested fix: 
disable history.back() while timers are still playing

Having a hook (e.g. `cancelAnimatino` or similar) to be able to implement [GSAP's timeline.reverse()](https://greensock.com/docs/TimelineLite/reverse()) could be interesting.

**Comment by TylerBarnes** [comment]
Upgrade to `v1.7.0` for a fix!
Apologies for the late response to this.
