### ISSUE TITLE
[suggestion] Measure (similar) component on next page

### ISSUE THREAD

**Issue by flowen** [TylerBarnes/gatsby-plugin-transition-link#53]
As we spoke by email, I thought I would just add the suggestion here. 

Being able to measure components on the next page would be an awesome way for morphing animations. As the nature of the web is dynamic, unless we use fixed dimensions, most morphing transitions won't work without this.

**Comment by TylerBarnes** [comment]
I love this idea. I'm thinking there might be a way to do it potentially using promises.
Since the dom node of the next page may not exist yet, passing it as a property to the exit function wouldn't work. I can pass a promise instead and once the dom node exists, that promise will resolve and return the next pages dom node.
So it could be used like so:

```
<Link
	exit={{
		trigger: async ({node, entryNode}) => {
			const elToMeasure = await entryNode.querySelector('.el-to-measure');

			// use next page's element in the exit pages animation.
		}
	}}
>Go home</Link>
```

**Comment by TylerBarnes** [comment]
Actually.. In that case maybe there should just be a new trigger function prop directly on the link which returns both nodes as promises!

```jsx
<Link
exit={{
	...	
}}
entry={{
	...
}}
trigger={async ({exit, entry}) => {
	const exitNode = await exit();
	const entryNode = await entry();
}}
>Go home</Link>
```

**Comment by TylerBarnes** [comment]
To measure a dom element on the next page, we can remove the delay on the entering page and just hide it instead. Since it will exist, we can await both nodes, then animate when we have them.


```jsx
<Link
exit={{
  length: 1	
}}
entry={{
  length: 2
}}
trigger={async (pages) => {
  const exit = await pages.exit();
  const entry = await pages.entry(); 
  
  entry.node.style.opacity = "0";

  const elHeight = entry.node.querySelector('.el-to-measure'). offsetHeight

  // perform a gsap or anime.js animation based on this info!
  // this could even work with react-spring or react-pose if paired with react context to set the height via context here. FLIP animations would also be possible here.
}}
>Go home</Link>
```

**Comment by flowen** [comment]
I don't see any immediate arguments against this, so great idea! 

Having both nodes is the key for morphing transitions between 2 pages. 
I can only imagine that the trigger prop will become a huge block of code for very custom animations, but perhaps that's part of it.

**Comment by TylerBarnes** [comment]
upgrade to `v1.9.0` for the new trigger prop!!

As mentioned before, this prop takes a function that receives a pages argument containing promises for both the entering and exiting pages. Once the promise resolves it contains all the exit/entry settings (delay, duration, etc) as well as the dom node for each page.

This is the current API:
```jsx
<Link
exit={{
  length: 1	
}}
entry={{
  length: 2
}}
trigger={async (pages) => {
  const exit = await pages.exit;
  const entry = await pages.entry; 
  
  entry.node.style.opacity = "0";

  const elHeight = entry.node.querySelector('.el-to-measure').offsetHeight

  // perform a gsap or anime.js animation based on this info!
  // this could even work with react-spring or react-pose if paired with react context to set the height via context here. FLIP animations would also be possible here.
}}
>Go home</Link>
```

I think to go along with this, entry needs a new setting `revealAfter` to render the entering page but keep it hidden for x amount of time.

```
<Link
exit={{
  length: 2
}}
entry={{
  revealAfter: 1
}}
trigger={...}
>
```

In the above example both pages immediately render but the second page isn't visible for a second. This way we can measure elements on that page and then animate both pages as needed to morph elements into other elements!

**Comment by TylerBarnes** [comment]
Oops! Upgrade to `v1.9.1` so that the new trigger function doesn't break old TransitionLinks! 😂

**Comment by TylerBarnes** [comment]
On second thought it might just be easier to make rendering the next page immediately but hidden a default when using the delay setting.. I'll have to do some playing around to see.

**Comment by TylerBarnes** [comment]
Hmm, I think this needs some more work actually. 
The functionality is there but I'll need to do more testing / tweaking to get the DX right.

**Comment by TylerBarnes** [comment]
If you have time to try it out it would be awesome to get your feedback.

```jsx
            entry={{
              appearAfter: 2,
              length: 1,
            }}
            trigger={async pages => {
              const exit = await pages.exit
              const entry = await pages.entry
              
              // measure entry element here
              // start exit animation based on measurements if you want

              // wait for the entering page to become visible
              await entry.visible

              // the entering page is visible here.
              // if you want you can animate it here.
              
            }}
```

**Comment by TylerBarnes** [comment]
Ok, had a chance to check this out again tonight with fresh eyes.

I think it's good actually. I went one step better and made you an AniLink with morphing capabilities!

Check https://gatsby-plugin-transition-link.netlify.com/morph/ and click the red square.

Upgrade to the latest TL and do this:

```jsx
    <AniLink
      morph
      to="/morph/b"
      duration={1}
      morph={{
        from: '#js-small-box',
        to: '#js-big-box',
      }}
    >
      <div
        id="js-small-box"
        style={{
          background: 'red',
          width: '100px',
          height: '100px',
        }}
      />
    </AniLink>
```

If it doesn't fit your needs you can check the code at https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/master/src/AniLink/MorphTo.js

Let me know if you need any more help!

**Comment by TylerBarnes** [comment]
Just added this to the docs like 1 yr later 😆
