### ISSUE TITLE
Unable to get property 'scrollTop' of undefined or null reference

### ISSUE THREAD

**Issue by jacekk** [TylerBarnes/gatsby-plugin-transition-link#56]
OS: **Win 10**
Browser: **IE 11**

![image](https://user-images.githubusercontent.com/1695878/54604988-6ee34680-4a48-11e9-85f1-19f47d1fde12.png)

**Comment by TylerBarnes** [comment]
fixed in #57 
Thanks!

**Comment by TylerBarnes** [comment]
released in `v1.6.1`
