### ISSUE TITLE
Provide hook for TransitionState

### ISSUE THREAD

**Issue by hmbrg** [TylerBarnes/gatsby-plugin-transition-link#60]
I think it would make sense to provide a React Hook that makes the Transition state accessible.

**Comment by TylerBarnes** [comment]
I agree! This should be pretty easy. I had this as a plan for v2 in #42 but I've been implementing alot of those features one by one in v1 so I'll add this to my todo list!

**Comment by TylerBarnes** [comment]
Upgrade to `v1.10.0` for `useTransitionState` hook.

This ended up being far easier than expected!

Use like:

```jsx
import React, { memo } from 'react'
import { useTransitionState } from 'gatsby-plugin-transition-link/hooks'

const TestHooksComponent = memo() => {
  const state = useTransitionState()
  const { mount, current, exit, entry } = state

  return <div>{mount ? 'mounting!' : 'no mount for you'}</div>
})
```

note: React.memo isn't absolutely necessary but in my tests this component was rendering extra times.

**Comment by TylerBarnes** [comment]
React is amazing. Check out how easy this was...

```jsx
import { useContext } from "react";
import { publicContext } from "../context/createTransitionContext";

const useTransitionState = () => useContext(publicContext);

export { useTransitionState };
```
