### ISSUE TITLE
How to use with CSSTransition

### ISSUE THREAD

**Issue by hmbrg** [TylerBarnes/gatsby-plugin-transition-link#64]
When using CSSTransition to replicate the `cover`-Transition from AniLink, the `TransitionPortal` seems to remount on page change. This abruptly stops the CSS transition.

My Layout component gets wrapped by this:
```javascript
export default function NavTransition(props) {
  return (
    <TransitionState>
      {({ transitionStatus: sstatus }) => {
        return (
          <>
            {props.children}
            <TransitionPortal>
              <TransitionEffect active={sstatus === 'exiting'} />
            </TransitionPortal>
          </>
        )
      }}
    </TransitionState>
  )
}
```

`TransitionEffect` is a component using CSSTransition and works outside the `TransitionPortal`. The component looks something like this:
```javascript
function TransitionEffect({ active }) {
  const [inFirst, setInFirst] = useState(false);

  useEffect(() => {
    setInFirst(active);
  }, [active]);

  return (
    <>
      <CSSTransition
        in={inFirst}
        timeout={duration}
        classNames="first"
        onEntered={(el, isAppearing) => {
          setInFirst(false);
        }}>
        <div className="first" />
      </CSSTransition>
    </>
  );
}
```

What am I missing, why does the Portal get remounted or rerendered? Is there any example with using CSS Transitions?

**Comment by TylerBarnes** [comment]
That's odd! Which version are you on and do you have a demo repo I could debug with?
I can't say why that would happen off the top of my head.

One thing I do notice is that you're just checking if the status is `exiting`. I would recommend checking for `exiting` and `exited`. There's also an undocumented render prop `mount` to check for either which was added recently.

```jsx
export default function NavTransition(props) {
  return (
    <TransitionState>
      {({ mount }) => {
        return (
          <>
            {props.children}
            <TransitionPortal>
              <TransitionEffect active={mount} />
              {/* or */}
              <TransitionEffect active={!mount} />
            </TransitionPortal>
          </>
        )
      }}
    </TransitionState>
  )
}
```

That might not be the issue though. It would be great to be able to debug this on your site.

**Comment by TylerBarnes** [comment]
Hey @hmbrg, closing this out as stale. if you still need help please reopen this issue or open another issue and provide a repro for me to see the problem.
