### ISSUE TITLE
AniLink Swipe up and down are glitchy

### ISSUE THREAD

**Issue by TylerBarnes** [TylerBarnes/gatsby-plugin-transition-link#66]
Looks like some change to the way TransitionLink works has caused vertical swipe animations to be glitchy. Probably an easy fix!

**Comment by TylerBarnes** [comment]
Hmm, looks like it's more difficult to get these animations working than I thought. It's doable but doesn't feel worth it since I've never liked the swipe animations very much and they've been buggy for a while. I'm going to partially deprecate the swipe animation by removing it from the documentation. If there's anyone that wants to keep using it or wants to spend the time to make a PR making the swipe animations buttery smooth, PR's are welcome!

**Comment by mkimbo** [comment]
Hello, I am using the cover animation for transition from 1 page to the next and it also shows an extra scrollbar for a split second and this makes the page jumpy..Is there any fix for this double scrollbar issue?

**Comment by Hahlh** [comment]
I also experience this issue. 

It first occurred after I started using the layout option through the config.
Curiously it only happens on one page:
![Peek 2021-02-01 23-03](https://user-images.githubusercontent.com/45669613/106523909-202ae280-64e2-11eb-8cfc-13d69a2dd09b.gif)

 The page seems to be limited in height first and as the second elements get triggered through intersection observer (gatsby-plugin-scroll-reveal) it extends. The second scrollbar vanishes as soon as the page end is reached.

I will have to deploy this site tomorrow morning and this bug only occurred now. I will play a little bit around, but if I can't find any quick fix, I will try to revert to not using the layout option and see whether that solves it.

**Comment by Hahlh** [comment]
A simple additional overflow-y: hidden on .tl-edges seems to do the job.
