### ISSUE TITLE
Add passing state & replace history option like in Gatsby Link & navigate function ?

### ISSUE THREAD

**Issue by dodikuswono** [TylerBarnes/gatsby-plugin-transition-link#72]
In Gatsby Link & navigate function there's options to:

- Pass state values that will be available in location.state in the target page’s props
- replace the current URL in history

TransitionLink & AniLink currently not these options.

**Comment by Shriken** [comment]
Any work around for this? its killing me here

**Comment by TylerBarnes** [comment]
Hey @Shriken apologies on the late response! I put this away in my mind as a todo but never actually put it on a real list.
I'll get this fixed this week.

**Comment by ITSjwags** [comment]
This is great. I've been struggling with the same thing here.

**Comment by TylerBarnes** [comment]
Hey guys, this is fixed in `v1.12.2`!

**Comment by Shriken** [comment]
@TylerBarnes you are amazing. I really appreciate your work so many many thanks and good karma for life! ^_^
