### ISSUE TITLE
No transition on links with #ExampleID

### ISSUE THREAD

**Issue by joebentaylor** [TylerBarnes/gatsby-plugin-transition-link#83]
Page transition only works if you dont use an # in your URL.

For example:

Going from `example.site` to `example.site/page` is totally fine when you click an AniLink button.

However if you wish to visit a point in the next page like so, the transition doesnt work.
`example.site` to `example.site/page#sectionTwo` Why cant we do this?

**Comment by lkhphuc** [comment]
Have the same issue there. Any update on this one?
Did you find a workaround for this yourself @joebentaylor ?

**Comment by timmysmalls** [comment]
This is the problem I'm also facing with this plugin. I'd love to know if there's some way around this. I've tried hacky workarounds like setting a timeout to scroll to the anchor x milliseconds after the page has transitioned, but this is a. inconsistent, and b. ugly as hell. I'm sure there must be a more elegant solution.

**Comment by TylerBarnes** [comment]
Hey guys, I just added a fix for this in `gatsby-plugin-transition-link@1.17.2`. Try it out and let me know what you think!

**Comment by timmysmalls** [comment]
@TylerBarnes That's really awesome dude! Thanks a million! I'll check it out as soon as I get a chance!

**Comment by EricWVGG** [comment]
Has this issue regressed? I'm afraid it's not working at all for me.
