### ISSUE TITLE
Cmd + Click (Mac) and Ctrl + Click (Windows) to open a new tab

### ISSUE THREAD

**Issue by pcooney10** [TylerBarnes/gatsby-plugin-transition-link#85]
Hey, cool library !

With `gatsby-link`, cmd + click opens a link in a new tab. This same behavior does not seem to be present in `gatsby-plugin-transition-link`.

Is it possible for us to still enable this behavior without breaking the inner workings of the library?

**Comment by TylerBarnes** [comment]
Thanks again @pcooney10 , upgrade to gatsby-plugin-transition-link@1.12.4 to use your contribution!
