### ISSUE TITLE
Deploying on gh-pages breaks AniLink

### ISSUE THREAD

**Issue by antonisierakowski** [TylerBarnes/gatsby-plugin-transition-link#91]
While working on my project I realized that despite working fine in develop mode, as well as on gatsby serve, the transitions implemented with AniLink component don't work at all when deployed on gh-pages. I thought that it's probably me who messed something up in my project, but after creating a new gatsby project with default starter, and then replacing the default Link components with AniLinks, they still don't work when deployed on gh-pages, despite working fine in development version.
Here's the repo with reproduced behavior: https://github.com/antonisierakowski/test-anilink
And here it is deployed on gh-pages: https://antonisierakowski.github.io/test-anilink/
Could that be a problem with gsap library?

**Comment by Webstudions** [comment]
I'm experiencing a similar issue. While running gatsby develop, AniLink animations are working. 
On gatsby build or gatsby serve, animations don't seem to be working.

**Comment by kasia-basia** [comment]
Hey, did anyone figure it out? I'm having the same problem with AniLink when running gatsby build.

**Comment by ajz003** [comment]
I'm having this issue as well. It works fine for me on `gatsby develop` and `gatsby serve`, but the animations simply don't happen on gh-pages. I hosted the same repo on Heroku and the animations work there.

**Comment by TylerBarnes** [comment]
Hey everyone, sorry for the delay on this. I'm not sure why this was happening but after I upgraded all Gatsby packages, transition link, and React in the example repo above, and then deployed to GH pages after building with `gatsby build --prefix-paths` it deployed and works fine. https://tylerbarnes.github.io/test-anilink/

Please upgrade transition link to the latest version and make sure your deploy process includes building with `gatsby build --prefix-paths`. Also make sure you've added a path prefix if you're deploying to a sub directory.
https://www.gatsbyjs.org/docs/path-prefix/
